apiVersion: v1
kind: Service
metadata:
  annotations:
    enzo: "true"
  labels:
    app: rachel-pipeline-from-scratch
    app.kubernetes.io/instance: rachel-pipeline-from-scratch
    app.kubernetes.io/name: rachel-pipeline-from-scratch
  name: rachel-pipeline-from-scratch
  namespace: rachel-pipeline-from-scratch
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: rachel-pipeline-from-scratch
    app.kubernetes.io/name: rachel-pipeline-from-scratch
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/rc12306/Cloud-Native-Bootcamp-App
    enzo: "true"
  labels:
    app: rachel-pipeline-from-scratch
    app.kubernetes.io/instance: rachel-pipeline-from-scratch
    app.kubernetes.io/name: rachel-pipeline-from-scratch
    app.openshift.io/runtime: js
  name: rachel-pipeline-from-scratch
  namespace: rachel-pipeline-from-scratch
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: rachel-pipeline-from-scratch
      app.kubernetes.io/name: rachel-pipeline-from-scratch
  template:
    metadata:
      annotations:
        enzo: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rachel-pipeline-from-scratch
        app.kubernetes.io/name: rachel-pipeline-from-scratch
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/rachel_chua_ibm/cloud-native-bootcamp-app:ddc72bd6aaf8adfef46f9168664d6f44cba1a55e
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: rachel-pipeline-from-scratch
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
    enzo: "true"
    openshift.io/host.generated: "true"
  name: rachel-pipeline-from-scratch
  namespace: rachel-pipeline-from-scratch
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: rachel-pipeline-from-scratch
    weight: 100
  wildcardPolicy: None
